# Generated by Django 5.1.1 on 2024-10-09 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watches', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='list_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='watchmovement',
            name='movement_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
