# Generated by Django 5.1.1 on 2024-10-22 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watches', '0002_alter_watchlist_list_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='slug',
            field=models.SlugField(blank=True, max_length=120, null=True, unique=True),
        ),
    ]
