# Generated by Django 5.1.1 on 2024-10-22 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watches', '0003_watchlist_friendly_name_alter_watchlist_list_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='friendly_name',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
