# Generated by Django 5.1.1 on 2024-10-22 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watches', '0004_alter_watchlist_friendly_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='friendly_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
