# Generated by Django 5.1.1 on 2024-10-22 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watches', '0005_alter_watchlist_friendly_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='watch',
            options={'verbose_name_plural': 'Watches'},
        ),
        migrations.AlterModelOptions(
            name='watchlist',
            options={'ordering': ['friendly_name']},
        ),
        migrations.AddField(
            model_name='watchlist',
            name='list_order',
            field=models.IntegerField(default=2),
        ),
    ]
