# Generated by Django 5.1.1 on 2024-11-05 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watches', '0006_alter_watch_options_alter_watchlist_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='watchlist',
            options={'ordering': ['list_order', 'friendly_name']},
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='friendly_name',
            field=models.CharField(max_length=100, unique=True, verbose_name=' name'),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='list_order',
            field=models.IntegerField(default=1000),
        ),
        migrations.AlterField(
            model_name='watchmovement',
            name='movement_name',
            field=models.CharField(max_length=100, unique=True, verbose_name=' name'),
        ),
    ]
